"""New Services Structure

Revision ID: b21da46fe919
Revises: 03bd4510820c
Create Date: 2025-08-21 23:06:10.923568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21da46fe919'
down_revision: Union[str, None] = '03bd4510820c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'vulnerability_assignments', 'cves', ['cve_id'], ['cve_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vulnerability_assignments', type_='foreignkey')
    # ### end Alembic commands ###
